package pojo;
// Generated Jun 12, 2020 11:24:48 AM by Hibernate Tools 4.3.1



/**
 * DanhsachlopId generated by hbm2java
 */
public class DanhsachlopId  implements java.io.Serializable {


     private String mamon;
     private String masv;
     private String malop;

    public DanhsachlopId() {
    }

    public DanhsachlopId(String mamon, String masv, String malop) {
        this.mamon = mamon;
        this.masv = masv;
        this.malop = malop;
    }

    public String getMamon() {
        return mamon;
    }

    public void setMamon(String mamon) {
        this.mamon = mamon;
    }

    public String getMasv() {
        return masv;
    }

    public void setMasv(String masv) {
        this.masv = masv;
    }

    public String getMalop() {
        return malop;
    }

    public void setMalop(String malop) {
        this.malop = malop;
    }

    


}


