package pojo;
// Generated Jun 12, 2020 11:24:48 AM by Hibernate Tools 4.3.1



/**
 * Danhsachlop generated by hbm2java
 */
public class Danhsachlop  implements java.io.Serializable {


     private DanhsachlopId id;

    public Danhsachlop() {
    }

    public Danhsachlop(DanhsachlopId id) {
       this.id = id;
    }
   
    public DanhsachlopId getId() {
        return this.id;
    }
    
    public void setId(DanhsachlopId id) {
        this.id = id;
    }




}


