package pojo;
// Generated Jun 12, 2020 11:24:48 AM by Hibernate Tools 4.3.1



/**
 * Lop generated by hbm2java
 */
public class Lop  implements java.io.Serializable {


     private String malop;

    public Lop() {
    }

    public Lop(String malop) {
        this.malop = malop;
    }

    
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }




}


