package pojo;
// Generated Jun 12, 2020 11:24:48 AM by Hibernate Tools 4.3.1



/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String mamon;
     private String tenmon;
     private String phong;
     private Lop lop;

    public Monhoc() {
        this.lop = new Lop();
    }

	
    public Monhoc(String mamon) {
        this.mamon = mamon;
    }
    public Monhoc(String mamon, String tenmon, String phong, Lop lop) {
       this.mamon = mamon;
       this.tenmon = tenmon;
       this.phong = phong;
       this.lop = lop;
    }
   
    public String getMamon() {
        return this.mamon;
    }
    
    public void setMamon(String mamon) {
        this.mamon = mamon;
    }
    public String getTenmon() {
        return this.tenmon;
    }
    
    public void setTenmon(String tenmon) {
        this.tenmon = tenmon;
    }
    public String getPhong() {
        return this.phong;
    }
    
    public void setPhong(String phong) {
        this.phong = phong;
    }
    public Lop getLop() {
        return this.lop;
    }
    
    public void setMalop(Lop lop) {
        this.lop = lop;
    }

    public void setLop(Lop lop) {
        this.lop = lop;
    }




}


