package pojo;
// Generated Jun 12, 2020 11:24:48 AM by Hibernate Tools 4.3.1



/**
 * Sinhvien generated by hbm2java
 */
public class Sinhvien  implements java.io.Serializable {


     private String masv;
     private String hoten;
     private String gioitinh;
     private String cmnd;
     private String malop;

    public Sinhvien() {
    }

	
    public Sinhvien(String masv) {
        this.masv = masv;
    }
    public Sinhvien(String masv, String hoten, String gioitinh, String cmnd, String malop) {
       this.masv = masv;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.cmnd = cmnd;
       this.malop = malop;
    }
   
    public String getMasv() {
        return this.masv;
    }
    
    public void setMasv(String masv) {
        this.masv = masv;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public String getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(String gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(String cmnd) {
        this.cmnd = cmnd;
    }
    public String getMalop() {
        return this.malop;
    }
    
    public void setMalop(String malop) {
        this.malop = malop;
    }




}


